const colors = {
  light: {
    text: "#0D0D1A",
    tint: "#6C5CE7",
    background: "#F0F2FF",
    foreground: "#0D0D1A",
    card: "#FFFFFF",
    cardForeground: "#0D0D1A",
    primary: "#6C5CE7",
    primaryForeground: "#FFFFFF",
    secondary: "#E8EAF6",
    secondaryForeground: "#1A1A2E",
    muted: "#E8EAF6",
    mutedForeground: "#8B8FA8",
    accent: "#6C5CE7",
    accentForeground: "#FFFFFF",
    destructive: "#FF6B6B",
    destructiveForeground: "#FFFFFF",
    border: "#DDE0F5",
    input: "#FFFFFF",
    income: "#00B894",
    expense: "#FF6B6B",
    warning: "#FDCB6E",
    success: "#00B894",
    gradientStart: "#6C5CE7",
    gradientEnd: "#A29BFE",
  },
  dark: {
    text: "#F0F2FF",
    tint: "#A29BFE",
    background: "#0D0D1A",
    foreground: "#F0F2FF",
    card: "#1A1A2E",
    cardForeground: "#F0F2FF",
    primary: "#A29BFE",
    primaryForeground: "#0D0D1A",
    secondary: "#252540",
    secondaryForeground: "#F0F2FF",
    muted: "#252540",
    mutedForeground: "#6B7399",
    accent: "#A29BFE",
    accentForeground: "#0D0D1A",
    destructive: "#FF6B6B",
    destructiveForeground: "#FFFFFF",
    border: "#252540",
    input: "#1A1A2E",
    income: "#00B894",
    expense: "#FF6B6B",
    warning: "#FDCB6E",
    success: "#00B894",
    gradientStart: "#252540",
    gradientEnd: "#1A1A2E",
  },
  radius: 16,
};

export default colors;
