import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import React, { useMemo, useState } from "react";
import { Alert, Platform, ScrollView, Share, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { CATEGORIES, getCategoryById } from "@/constants/categories";
import { useTransactions } from "@/context/TransactionContext";
import { useAuth } from "@/context/AuthContext";
import { useColors } from "@/hooks/useColors";
import { PieChart } from "@/components/PieChart";

type Period = "weekly" | "monthly";

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const DAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

function fmt(n: number) {
  return `₹${n.toLocaleString("en-IN", { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;
}
function fmtFull(n: number) {
  return `₹${n.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export default function AnalyticsScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const { user } = useAuth();
  const { transactions, totalIncome, totalExpenses, balance, thisMonthIncome, thisMonthExpenses } = useTransactions();
  const [period, setPeriod] = useState<Period>("monthly");

  const topPad = Platform.OS === "web" ? 67 : insets.top;
  const bottomPad = Platform.OS === "web" ? 34 + 84 : 100;
  const now = new Date();

  const pieData = useMemo(() => {
    const byCategory: Record<string, number> = {};
    transactions.filter((t) => t.type === "expense").forEach((t) => {
      byCategory[t.category] = (byCategory[t.category] ?? 0) + t.amount;
    });
    return Object.entries(byCategory)
      .map(([id, value]) => { const cat = getCategoryById(id); return { value, color: cat.color, label: cat.name }; })
      .sort((a, b) => b.value - a.value)
      .slice(0, 6);
  }, [transactions]);

  const barData = useMemo(() => {
    if (period === "monthly") {
      return Array.from({ length: 6 }, (_, i) => {
        const d = new Date(now.getFullYear(), now.getMonth() - (5 - i), 1);
        const filter = (type: string) =>
          transactions.filter((t) => {
            const td = new Date(t.date + "T12:00:00");
            return t.type === type && td.getMonth() === d.getMonth() && td.getFullYear() === d.getFullYear();
          }).reduce((s, t) => s + t.amount, 0);
        return { label: MONTHS[d.getMonth()], income: filter("income"), expense: filter("expense") };
      });
    }
    return Array.from({ length: 7 }, (_, i) => {
      const d = new Date();
      d.setDate(d.getDate() - (6 - i));
      const filter = (type: string) =>
        transactions.filter((t) => {
          const td = new Date(t.date + "T12:00:00");
          return t.type === type && td.toDateString() === d.toDateString();
        }).reduce((s, t) => s + t.amount, 0);
      return { label: DAYS[d.getDay()], income: filter("income"), expense: filter("expense") };
    });
  }, [transactions, period]);

  const maxBar = Math.max(...barData.map((d) => Math.max(d.income, d.expense)), 1);

  const topCategories = useMemo(() => {
    const byCategory: Record<string, number> = {};
    transactions.filter((t) => t.type === "expense").forEach((t) => {
      byCategory[t.category] = (byCategory[t.category] ?? 0) + t.amount;
    });
    return Object.entries(byCategory)
      .map(([id, amount]) => ({ id, amount, cat: getCategoryById(id) }))
      .sort((a, b) => b.amount - a.amount)
      .slice(0, 6);
  }, [transactions]);

  const savingsRate = totalIncome > 0 ? ((totalIncome - totalExpenses) / totalIncome) * 100 : 0;

  function handleExportReport() {
    const monthName = MONTHS[now.getMonth()];
    const year = now.getFullYear();
    const topCatLines = topCategories.slice(0, 5).map((c, i) => `  ${i + 1}. ${c.cat.name}: ${fmtFull(c.amount)}`).join("\n");
    const report = `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📊 SpendWise Monthly Report
${monthName} ${year} · ${user?.username ?? "User"}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

💰 SUMMARY
  Total Income:    ${fmtFull(totalIncome)}
  Total Expenses:  ${fmtFull(totalExpenses)}
  Net Balance:     ${fmtFull(balance)}
  Savings Rate:    ${Math.max(savingsRate, 0).toFixed(1)}%

📅 THIS MONTH
  Income:    ${fmtFull(thisMonthIncome)}
  Expenses:  ${fmtFull(thisMonthExpenses)}
  Net:       ${fmtFull(thisMonthIncome - thisMonthExpenses)}

🏷 TOP EXPENSE CATEGORIES
${topCatLines || "  No expenses recorded"}

📈 TRANSACTIONS
  Total: ${transactions.length}
  Income entries: ${transactions.filter((t) => t.type === "income").length}
  Expense entries: ${transactions.filter((t) => t.type === "expense").length}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by SpendWise
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`.trim();

    if (Platform.OS === "web") {
      Alert.alert("Monthly Report", report);
    } else {
      Share.share({ message: report, title: `SpendWise Report - ${monthName} ${year}` });
    }
  }

  return (
    <ScrollView
      style={{ flex: 1, backgroundColor: colors.background }}
      contentContainerStyle={[styles.scroll, { paddingTop: topPad + 8, paddingBottom: bottomPad }]}
      showsVerticalScrollIndicator={false}
    >
      {/* Header */}
      <View style={styles.headerRow}>
        <Text style={[styles.pageTitle, { color: colors.foreground }]}>Analytics</Text>
        <TouchableOpacity
          onPress={handleExportReport}
          style={[styles.exportBtn, { backgroundColor: colors.card, borderColor: colors.border }]}
        >
          <Ionicons name="share-outline" size={16} color="#6C5CE7" />
          <Text style={[styles.exportText, { color: "#6C5CE7" }]}>Export</Text>
        </TouchableOpacity>
      </View>

      {/* Quick Stats */}
      <View style={styles.statsRow}>
        {[
          { label: "Income", value: fmt(totalIncome), color: "#00B894", icon: "arrow-up-circle" },
          { label: "Expenses", value: fmt(totalExpenses), color: "#FF6B6B", icon: "arrow-down-circle" },
          { label: "Savings %", value: `${Math.max(savingsRate, 0).toFixed(0)}%`, color: "#74B9FF", icon: "trending-up" },
        ].map((s) => (
          <View key={s.label} style={[styles.statCard, { backgroundColor: colors.card, borderColor: colors.border }]}>
            <View style={[styles.statIcon, { backgroundColor: s.color + "20" }]}>
              <Ionicons name={s.icon as any} size={16} color={s.color} />
            </View>
            <Text style={[styles.statValue, { color: s.color }]}>{s.value}</Text>
            <Text style={[styles.statLabel, { color: colors.mutedForeground }]}>{s.label}</Text>
          </View>
        ))}
      </View>

      {/* This Month Summary */}
      <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}>
        <Text style={[styles.cardTitle, { color: colors.foreground }]}>
          {MONTHS[now.getMonth()]} {now.getFullYear()} · Monthly Report
        </Text>
        <View style={styles.monthRow}>
          <View style={styles.monthItem}>
            <View style={[styles.monthDot, { backgroundColor: "#00B894" }]} />
            <Text style={[styles.monthLabel, { color: colors.mutedForeground }]}>Income</Text>
            <Text style={[styles.monthValue, { color: "#00B894" }]}>{fmt(thisMonthIncome)}</Text>
          </View>
          <View style={styles.monthItem}>
            <View style={[styles.monthDot, { backgroundColor: "#FF6B6B" }]} />
            <Text style={[styles.monthLabel, { color: colors.mutedForeground }]}>Expenses</Text>
            <Text style={[styles.monthValue, { color: "#FF6B6B" }]}>{fmt(thisMonthExpenses)}</Text>
          </View>
          <View style={styles.monthItem}>
            <View style={[styles.monthDot, { backgroundColor: "#6C5CE7" }]} />
            <Text style={[styles.monthLabel, { color: colors.mutedForeground }]}>Net</Text>
            <Text style={[styles.monthValue, { color: (thisMonthIncome - thisMonthExpenses) >= 0 ? "#00B894" : "#FF6B6B" }]}>
              {(thisMonthIncome - thisMonthExpenses) >= 0 ? "+" : ""}{fmt(thisMonthIncome - thisMonthExpenses)}
            </Text>
          </View>
        </View>
      </View>

      {/* Period Toggle */}
      <View style={[styles.segment, { backgroundColor: colors.muted }]}>
        {(["monthly", "weekly"] as Period[]).map((p) => (
          <TouchableOpacity key={p} onPress={() => setPeriod(p)} style={[styles.segBtn, period === p && styles.segBtnActive]}>
            {period === p ? (
              <LinearGradient colors={["#4834D4", "#6C5CE7"]} style={styles.segGrad} start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }}>
                <Text style={styles.segTextActive}>{p.charAt(0).toUpperCase() + p.slice(1)}</Text>
              </LinearGradient>
            ) : (
              <Text style={[styles.segTextInactive, { color: colors.mutedForeground }]}>{p.charAt(0).toUpperCase() + p.slice(1)}</Text>
            )}
          </TouchableOpacity>
        ))}
      </View>

      {/* Bar Chart */}
      <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}>
        <Text style={[styles.cardTitle, { color: colors.foreground }]}>
          {period === "monthly" ? "Income vs Expense — Last 6 Months" : "Income vs Expense — Last 7 Days"}
        </Text>
        {barData.every((d) => d.income === 0 && d.expense === 0) ? (
          <View style={styles.chartEmpty}>
            <Ionicons name="bar-chart-outline" size={40} color={colors.mutedForeground} />
            <Text style={[styles.emptyText, { color: colors.mutedForeground }]}>No data for this period</Text>
          </View>
        ) : (
          <>
            <View style={styles.barChart}>
              {barData.map((d, i) => (
                <View key={i} style={styles.barGroup}>
                  <View style={styles.bars}>
                    <View style={[styles.bar, { height: Math.max((d.income / maxBar) * 110, d.income > 0 ? 4 : 0), backgroundColor: "#00B894" }]} />
                    <View style={[styles.bar, { height: Math.max((d.expense / maxBar) * 110, d.expense > 0 ? 4 : 0), backgroundColor: "#FF6B6B" }]} />
                  </View>
                  <Text style={[styles.barLabel, { color: colors.mutedForeground }]}>{d.label}</Text>
                </View>
              ))}
            </View>
            <View style={styles.barLegend}>
              <View style={styles.legendItem}><View style={[styles.legendDot, { backgroundColor: "#00B894" }]} /><Text style={[styles.legendText, { color: colors.mutedForeground }]}>Income</Text></View>
              <View style={styles.legendItem}><View style={[styles.legendDot, { backgroundColor: "#FF6B6B" }]} /><Text style={[styles.legendText, { color: colors.mutedForeground }]}>Expense</Text></View>
            </View>
          </>
        )}
      </View>

      {/* Pie Chart */}
      {pieData.length > 0 && (
        <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}>
          <Text style={[styles.cardTitle, { color: colors.foreground }]}>Expense Breakdown</Text>
          <View style={styles.pieWrap}>
            <PieChart data={pieData} size={200} centerLabel="Total" centerValue={fmt(totalExpenses)} />
          </View>
          <View style={styles.pieLegend}>
            {pieData.map((d) => (
              <View key={d.label} style={styles.pieLegendItem}>
                <View style={[styles.legendDot, { backgroundColor: d.color }]} />
                <Text style={[styles.legendText, { color: colors.mutedForeground, flex: 1 }]} numberOfLines={1}>{d.label}</Text>
                <Text style={[styles.legendText, { color: colors.foreground, fontFamily: "Inter_600SemiBold" }]}>{fmt(d.value)}</Text>
              </View>
            ))}
          </View>
        </View>
      )}

      {/* Category Breakdown */}
      <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}>
        <Text style={[styles.cardTitle, { color: colors.foreground }]}>Spending by Category</Text>
        {topCategories.length === 0 ? (
          <View style={styles.chartEmpty}>
            <Ionicons name="pie-chart-outline" size={36} color={colors.mutedForeground} />
            <Text style={[styles.emptyText, { color: colors.mutedForeground }]}>No expenses recorded yet</Text>
          </View>
        ) : (
          <View style={{ gap: 16 }}>
            {topCategories.map((c) => {
              const pct = totalExpenses > 0 ? (c.amount / totalExpenses) * 100 : 0;
              return (
                <View key={c.id}>
                  <View style={styles.catRow}>
                    <View style={[styles.catDot, { backgroundColor: c.cat.color }]} />
                    <Text style={[styles.catName, { color: colors.foreground }]} numberOfLines={1}>{c.cat.name}</Text>
                    <Text style={[styles.catAmount, { color: "#FF6B6B" }]}>{fmt(c.amount)}</Text>
                    <Text style={[styles.catPct, { color: colors.mutedForeground }]}>{pct.toFixed(0)}%</Text>
                  </View>
                  <View style={[styles.catBarBg, { backgroundColor: colors.muted }]}>
                    <View style={[styles.catBarFill, { width: `${pct}%`, backgroundColor: c.cat.color }]} />
                  </View>
                </View>
              );
            })}
          </View>
        )}
      </View>

      {/* All-time Summary */}
      <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}>
        <Text style={[styles.cardTitle, { color: colors.foreground }]}>All-Time Summary</Text>
        <View style={styles.vsRow}>
          <View style={styles.vsItem}>
            <Text style={[styles.vsLabel, { color: colors.mutedForeground }]}>Income</Text>
            <Text style={[styles.vsAmount, { color: "#00B894" }]}>{fmtFull(totalIncome)}</Text>
          </View>
          <View style={[styles.vsDivider, { backgroundColor: colors.border }]} />
          <View style={styles.vsItem}>
            <Text style={[styles.vsLabel, { color: colors.mutedForeground }]}>Expense</Text>
            <Text style={[styles.vsAmount, { color: "#FF6B6B" }]}>{fmtFull(totalExpenses)}</Text>
          </View>
          <View style={[styles.vsDivider, { backgroundColor: colors.border }]} />
          <View style={styles.vsItem}>
            <Text style={[styles.vsLabel, { color: colors.mutedForeground }]}>Net</Text>
            <Text style={[styles.vsAmount, { color: balance >= 0 ? "#00B894" : "#FF6B6B" }]}>
              {balance >= 0 ? "+" : ""}{fmtFull(balance)}
            </Text>
          </View>
        </View>
        {(totalIncome + totalExpenses) > 0 && (
          <View style={[styles.vsBar, { backgroundColor: "#FF6B6B33" }]}>
            <View style={[styles.vsBarFill, { width: `${(totalIncome / (totalIncome + totalExpenses)) * 100}%`, backgroundColor: "#00B894" }]} />
          </View>
        )}
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  scroll: { paddingHorizontal: 16 },
  headerRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 16 },
  pageTitle: { fontSize: 26, fontFamily: "Inter_700Bold" },
  exportBtn: { flexDirection: "row", alignItems: "center", gap: 6, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8, borderWidth: 1 },
  exportText: { fontSize: 13, fontFamily: "Inter_600SemiBold" },
  statsRow: { flexDirection: "row", gap: 10, marginBottom: 16 },
  statCard: { flex: 1, borderRadius: 16, padding: 14, borderWidth: 1, alignItems: "flex-start", gap: 4 },
  statIcon: { width: 30, height: 30, borderRadius: 10, alignItems: "center", justifyContent: "center", marginBottom: 2 },
  statValue: { fontSize: 15, fontFamily: "Inter_700Bold" },
  statLabel: { fontSize: 11, fontFamily: "Inter_400Regular" },
  card: { borderRadius: 20, padding: 20, borderWidth: 1, marginBottom: 16 },
  cardTitle: { fontSize: 16, fontFamily: "Inter_700Bold", marginBottom: 16 },
  monthRow: { flexDirection: "row", gap: 4 },
  monthItem: { flex: 1, alignItems: "center", gap: 4 },
  monthDot: { width: 8, height: 8, borderRadius: 4 },
  monthLabel: { fontSize: 11, fontFamily: "Inter_400Regular" },
  monthValue: { fontSize: 14, fontFamily: "Inter_700Bold" },
  segment: { flexDirection: "row", borderRadius: 14, padding: 4, marginBottom: 16 },
  segBtn: { flex: 1, borderRadius: 10, overflow: "hidden" },
  segBtnActive: {},
  segGrad: { alignItems: "center", justifyContent: "center", paddingVertical: 10, borderRadius: 10 },
  segTextActive: { fontSize: 14, fontFamily: "Inter_600SemiBold", color: "#fff" },
  segTextInactive: { fontSize: 14, fontFamily: "Inter_500Medium", textAlign: "center", paddingVertical: 10 },
  barChart: { flexDirection: "row", alignItems: "flex-end", height: 130, gap: 2 },
  barGroup: { flex: 1, alignItems: "center", gap: 6 },
  bars: { flexDirection: "row", alignItems: "flex-end", gap: 2, height: 110 },
  bar: { width: 10, borderRadius: 5 },
  barLabel: { fontSize: 9, fontFamily: "Inter_400Regular" },
  barLegend: { flexDirection: "row", gap: 16, marginTop: 14 },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 6 },
  legendDot: { width: 8, height: 8, borderRadius: 4 },
  legendText: { fontSize: 12, fontFamily: "Inter_400Regular" },
  pieWrap: { alignItems: "center", marginBottom: 16 },
  pieLegend: { gap: 8 },
  pieLegendItem: { flexDirection: "row", alignItems: "center", gap: 8 },
  catRow: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 8 },
  catDot: { width: 10, height: 10, borderRadius: 5 },
  catName: { flex: 1, fontSize: 14, fontFamily: "Inter_500Medium" },
  catAmount: { fontSize: 14, fontFamily: "Inter_600SemiBold" },
  catPct: { fontSize: 12, fontFamily: "Inter_400Regular", minWidth: 34, textAlign: "right" },
  catBarBg: { height: 6, borderRadius: 3, overflow: "hidden" },
  catBarFill: { height: "100%", borderRadius: 3 },
  chartEmpty: { alignItems: "center", paddingVertical: 28, gap: 10 },
  emptyText: { fontSize: 13, fontFamily: "Inter_400Regular" },
  vsRow: { flexDirection: "row", alignItems: "center", marginBottom: 16 },
  vsItem: { flex: 1, alignItems: "center" },
  vsLabel: { fontSize: 12, fontFamily: "Inter_400Regular", marginBottom: 4 },
  vsAmount: { fontSize: 14, fontFamily: "Inter_700Bold" },
  vsDivider: { width: 1, height: 40 },
  vsBar: { height: 8, borderRadius: 4, overflow: "hidden" },
  vsBarFill: { height: "100%", borderRadius: 4 },
});
